### PR TITLE
Add the redis-server if not installed by other means

### PR DESCRIPTION
**Pull request by javierbertoli**

### CODE REVIEW

**Comment by javierbertoli** [comment]
@aboe76, mind you check and review, please?

**Review by aboe76 — COMMENTED** [review]
looks good, but shouldn't the defaults.yaml
have ```manage_redis: False```
to be backward compliant?

**Comment by aboe76** [comment]
@javierbertoli any idea why there isn't a merge button?

because LGTM!

**Comment by javierbertoli** [comment]
Ha! Was missing the "contributors" team in the permissions. Try now?

**Comment by aboe76** [comment]
Woot,

**Comment by javierbertoli** [comment]
Thanks!

**Pull request merged**
