### PR TITLE
refactor(semantic-release): align to template-formula

### LINKED ISSUE #3: [FEATURE] Update formula to be aligned with the template formula
### Is your feature request related to a problem?

Yes, the testing scaffold is outdated and fails, as discovered in #2 

### Describe the solution you'd like

Update the formula to be aligned with the other formulas in the org, following the template formula.

### PR DESCRIPTION
**Pull request by javierbertoli**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

### What type of PR is this?

Update the formula to be aligned to the rest of the formulas,

While at it, fixed an issue in the tests for services taking too long to start and failing.

#### Primary type

- [X] `[build]`    Changes related to the build system
- [X] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [X] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [X] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [X] `[docs]`     Documentation changes
- [X] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Related issues and/or pull requests

Should close #3 

### Documentation checklist

- [X] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Review by daks — APPROVED** [review]
Just an eyeball review but everything LGTM, thanks @javierbertoli for the job :)

**Comment by daks** [comment]
Can we merge this code? @javierbertoli & @myii?

**Comment by javierbertoli** [comment]
@daks I'd say so. @myii, if you don't find anything obvious missing, can you merge it?

**Review by myii — APPROVED** [review]

**Comment by myii** [comment]
@javierbertoli @daks Merged, thanks for your contributions, reviews and patience!

**Pull request merged**
