### PR TITLE
fix: enable_upstream_repo pillar usage

### PR DESCRIPTION
**Pull request by daks**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

### What type of PR is this?
A simple PR fixing a mismatch between `enable_upstream_repo` in `pillar.example` and the internal value used which was `use_upstream_repo`

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [X] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by javierbertoli** [comment]
@daks, a quick grep in my working dir shows that all the formulas managing a repo (that I have a copy of) use `use_upstream_repo` instead of `enable_upstream_repo`. A grep in a fresh clone of this formula shows that the only reference to `enable_upstream_repo` is in the `pillar.example` 

```
$ grep -R upstrea *
pillar.example:  enable_upstream_repo: true
rspamd/install.sls:{% if rspamd.use_upstream_repo -%}
rspamd/defaults.yaml:  use_upstream_repo: true
```
so I'd say that just fixing the pillar would be the best approach instead of changing the states to match the pillar?

**Comment by daks** [comment]
> so I'd say that just fixing the pillar would be the best approach instead of changing the states to match the pillar?

I'm OK with that solution too but it introduces a `BREAKING CHANGE`, that's the big difference. I think #4 must be merged first then.

**Comment by javierbertoli** [comment]
@daks, #4 was merged. Mind you rebase and update this PR?

**Comment by SuperTux88** [comment]
> > so I'd say that just fixing the pillar would be the best approach instead of changing the states to match the pillar?
> 
> I'm OK with that solution too but it introduces a `BREAKING CHANGE`, that's the big difference. I think #4 must be merged first then.

Using `use_upstream_repo` as suggested and just changing the pillar.example wouldn't be a breaking change. The way this PR is at the moment with changing it to `enable_upstream_repo` is a breaking change. So I also suggest to stay with `use_upstream_repo` and just fix the example.

**Comment by daks** [comment]
@javierbertoli PR rebased and ready.

_I don't know why I thought it would be a `BREAKING CHANGE`_

**Review by javierbertoli — APPROVED** [review]

**Comment by javierbertoli** [comment]
Thanks @daks and @SuperTux88 !

**Pull request merged**
